name: Natapp SSH

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure Natapp
      run: |
        wget https://cdn.natapp.cn/assets/downloads/clients/2_3_9/natapp_linux_amd64/natapp?version=20220415 -O natapp
        chmod a+x natapp
        echo '::echo::on'
        echo '::set-output name=action_echo::enabled'
        ./natapp -authtoken=e6f09b830104f9ad
        
